version: '2'
services:
  web:
    image: node:12.13.0-alpine
    command: node /usr/src/app/dist/microservice/src/index.js
    build:
      context: ./dist
      dockerfile: Dockerfile
    volumes:
      - .:/usr/src/app
    ports:
      - "8080:8080"